//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int idP { get; set; }
        public string nomP { get; set; }
        public int precio { get; set; }
        public int sedeP { get; set; }
    
        public virtual sede sede { get; set; }
    }
}
